FROM maven:3.6.0-jdk-11-slim AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f/home/app/pom.xml clean compile assembly:single

#
# Package stage
#
FROM openjdk:11-jre-slim
RUN mkdir /home/app
COPY --from=build /home/app/target/vatFlatFileToRedis-1.0-jar-with-dependencies.jar /usr/local/vatFlatFileToRedis-1.0-jar-with-dependencies.jar
ENTRYPOINT ["java","-jar","/usr/local/vatFlatFileToRedis-1.0-jar-with-dependencies.jar","/home/app/"  ]
